// This file is auto-generated by the TypeScript plugin

import type AjaxModule from "../../../modules/ajax/index.ts";
import type AlertModule from "../../../modules/alert/index.ts";

export type ModulesMap = {
  'core:ajax': typeof AjaxModule
  "core:alert": typeof AlertModule
}

export type ModuleId = keyof ModulesMap;
