import { defineBlocksWithJsonArray } from "blockly/core";

const keys = [
  ["%{BKY_KEYBOARD_KEYPRESSED_ANY}", "any"],
  ["%{BKY_KEYBOARD_KEYPRESSED_SPACE}", " "],
  ["%{BKY_KEYBOARD_KEYPRESSED_UP}", "ArrowUp"],
  ["%{BKY_KEYBOARD_KEYPRESSED_DOWN}", "ArrowDown"],
  ["%{BKY_KEYBOARD_KEYPRESSED_RIGHT}", "ArrowRight "],
  ["%{BKY_KEYBOARD_KEYPRESSED_LEFT}", "ArrowLeft"],
  ["a", "a"],
  ["b", "b"],
  ["c", "c"],
  ["d", "d"],
  ["e", "e"],
  ["f", "f"],
  ["g", "g"],
  ["h", "h"],
  ["i", "i"],
  ["j", "j"],
  ["k", "k"],
  ["l", "l"],
  ["m", "m"],
  ["n", "n"],
  ["o", "o"],
  ["p", "p"],
  ["q", "q"],
  ["r", "r"],
  ["s", "s"],
  ["t", "t"],
  ["u", "u"],
  ["v", "v"],
  ["w", "w"],
  ["x", "x"],
  ["y", "y"],
  ["z", "z"],
  ["0", "0"],
  ["1", "1"],
  ["2", "2"],
  ["3", "3"],
  ["4", "4"],
  ["5", "5"],
  ["6", "6"],
  ["7", "7"],
  ["8", "8"],
  ["9", "9"],
];

defineBlocksWithJsonArray([
  {
    type: "keyboard_keypressed",
    message0: "%{BKY_KEYBOARD_KEYPRESSED}",
    args0: [
      {
        type: "field_dropdown",
        name: "KEY",
        options: keys,
      },
    ],
    message1: "%{BKY_KEYBOARD_KEYPRESSED_THEN}",
    args1: [
      {
        type: "input_statement",
        name: "STATEMENT",
      },
    ],
    style: "trigger_blocks",
    tooltip: "%{BKY_KEYBOARD_KEYPRESSED_TOOLTIP}",
    helpUrl: "%{BKY_KEYBOARD_KEYPRESSED_HELPURL}",
  },
]);
