import { defineBlocksWithJsonArray } from "blockly/core";

defineBlocksWithJsonArray([
  {
    type: "media_get_duration",
    message0: "%{BKY_MEDIA_GET_DURATION}",
    output: "Number",
    style: "variable_blocks",
    tooltip: "%{BKY_MEDIA_GET_DURATION_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_GET_DURATION_HELPURL}",
  },
  {
    type: "media_get_time",
    message0: "%{BKY_MEDIA_GET_TIME}",
    output: "Number",
    style: "variable_blocks",
    tooltip: "%{BKY_MEDIA_GET_TIME_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_GET_TIME_HELPURL}",
  },
  {
    type: "media_set_time",
    message0: "%{BKY_MEDIA_SET_TIME}",
    args0: [
      {
        type: "input_value",
        name: "VALUE",
        check: "Number",
      },
    ],
    previousStatement: null,
    nextStatement: null,
    style: "variable_blocks",
    tooltip: "%{BKY_MEDIA_SET_TIME_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_SET_TIME_HELPURL}",
  },
  {
    type: "media_playing",
    message0: "%{BKY_MEDIA_PLAYING}",
    output: "Boolean",
    style: "variable_blocks",
    tooltip: "%{BKY_MEDIA_PLAYING_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_PLAYING_HELPURL}",
  },
  {
    type: "media_play",
    message0: "%{BKY_MEDIA_PLAY}",
    previousStatement: null,
    nextStatement: null,
    style: "actions_blocks",
    tooltip: "%{BKY_MEDIA_PLAY_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_PLAY_HELPURL}",
  },
  {
    type: "media_play_excerpt",
    message0: "%{BKY_MEDIA_PLAY_EXCERPT}",
    args0: [
      {
        type: "input_value",
        name: "FROM",
        check: "Number",
      },
      {
        type: "input_value",
        name: "TO",
        check: "Number",
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    style: "actions_blocks",
    tooltip: "%{BKY_MEDIA_PLAY_EXCERPT_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_PLAY_EXCERPT_HELPURL}",
  },
  {
    type: "media_pause",
    message0: "%{BKY_MEDIA_PAUSE}",
    previousStatement: null,
    nextStatement: null,
    style: "actions_blocks",
    tooltip: "%{BKY_MEDIA_PAUSE_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_PAUSE_HELPURL}",
  },
  {
    type: "media_stop",
    message0: "%{BKY_MEDIA_STOP}",
    previousStatement: null,
    nextStatement: null,
    style: "actions_blocks",
    tooltip: "%{BKY_MEDIA_STOP_TOOLTIP}",
    helpUrl: "%{BKY_MEDIA_STOP_HELPURL}",
  },
]);
