<?php

/**
 * Implements hook_permission().
 */
function metascore_editor_permission() {

  return array(
    'access metascore editor' => array(
      'title' => t('access the metaScore editor'),
    ),
  );
  
}

/**
 * Implements hook_menu().
 */
function metascore_editor_menu() {

  $items = array();
  
  $items['editor'] = array(
    'title' => 'Editor',
    'page callback' => '_metascore_editor_menu_callback',
    'access arguments' => array('access metascore editor'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
   
}

/**
 * Menu callback.
 */
function _metascore_editor_menu_callback(){

  $metaScore_library = libraries_get_path('metaScore');

  return array(
    'interface' => array(
      '#type' => 'markup',
      '#markup' => '<div id="editor-wrapper"></div>',
      '#attached' => array(
        'css' => array(
          $metaScore_library .'/metaScore-editor.css',
        ),
        'js' => array(
          $metaScore_library .'/metaScore.min.js',
          drupal_get_path('module', 'metascore_editor') .'/metascore_editor.js',
        ),
      ),
    ),
  );

}

function metascore_editor_theme(){

  return array(
    'editor_page' =>  array(
      'template' => 'theme/editor-page',
      'render element' => 'page'
    ),
  );
  
}

function metascore_editor_preprocess_page(&$variables, $hook) {

  if(current_path() == 'editor'){  
    $variables['theme_hook_suggestions'][] = 'editor_page';
  }
  
}