// This file is auto-generated by the metascore-library:generate-types vite plugin

import type AjaxModule from "../src/core/modules/ajax/index.ts";
import type AlertModule from "../src/core/modules/alert/index.ts";
import type AppComponentsModule from "../src/core/modules/app_components/index.ts";
import type AssetsManagerModule from "../src/core/modules/assets_manager/index.ts";
import type AutoFocusModule from "../src/core/modules/auto_focus/index.ts";
import type BaseButtonModule from "../src/core/modules/button/index.ts";
import type ConfirmModule from "../src/core/modules/confirm/index.ts";
import type ContextMenuModule from "../src/core/modules/contextmenu/index.ts";
import type MediaCuepointsModule from "../src/core/modules/media_cuepoints/index.ts";
import type MediaPlayerModule from "../src/core/modules/media_player/index.ts";
import type ModalModule from "../src/core/modules/modal/index.ts";
import type ProgressIndicatorModule from "../src/core/modules/progress_indicator/index.ts";

declare module '../src/core/services/module-manager' {
  export interface ModulesMap {
    "core:ajax": typeof AjaxModule
    "core:alert": typeof AlertModule
    "core:app_components": typeof AppComponentsModule
    "core:assets_manager": typeof AssetsManagerModule
    "core:auto_focus": typeof AutoFocusModule
    "core:base_button": typeof BaseButtonModule
    "core:confirm": typeof ConfirmModule
    "core:contextmenu": typeof ContextMenuModule
    "core:media_cuepoints": typeof MediaCuepointsModule
    "core:media_player": typeof MediaPlayerModule
    "core:modal": typeof ModalModule
    "core:progress_indicator": typeof ProgressIndicatorModule
  }
}